log:
  console:
    level: info
  file:
    level: debug
    path: "./logs/server.log"
    rotationTime: 86400 # 24 hours
    maxAge: 604800 # 7 days
database:
  connStr: dev:password@tcp(127.0.0.1:3306)/addressbook
grpc:
  bindAddress: :50051
web:
  bindAddress: :8090